### ISSUE TITLE
Play method in struct Spotify does not queue

### ISSUE THREAD

**Issue by dissolete** [SplittyDev/spotify-rs#3]
It seems that calling the "play" method for the Spotify struct doesn't actually add songs to queue. Instead, calling this method just stops whatever song was last playing and plays the new one requested. For example, the line of code

`
spotify.play(String::from("track url"), false);
`

does the same thing as

`
spotify.play(String::from("track url"), true);
`

i.e., changing the "queue" flag from true to false doesn't change the behavior of the method.

I just created a queue on the code end to store requested tracks. That's fine, but it'd be better if the expected method queues songs on Spotify's end. Perhaps I am overlooking something?

**Comment by SplittyDev** [comment]
Hey, thanks for the bug report, I'll definitely look into this!

**Comment by SplittyDev** [comment]
@dissolete after some research, it appears that SpotifyWebHelper *should*, in theory, support the `?action=queue` parameter, but doesn't actually respond to it.

I've also contacted the developer of another Spotify API, @nikxda, who confirmed that the feature doesn't work as it's supposed to.

Therefore, I'm going to remove the queue functionality from the code entirely. Since you already use a local queue in your software, that shouldn't introduce any new bugs or unexpected behavior on your end.

Feel free to respond if you have any other questions, or maybe even a better idea how to handle that issue :)
