### ISSUE TITLE
Local API no longer available

### ISSUE THREAD

**Issue by embediver** [SplittyDev/spotify-rs#8]
As you did also suspect, the local API doesn't seem to be available any more.

I stumbled across this lib when searching crates.io and was pleased how straight forward the local API was, but realized after a short investigation, it doesn't seem to exist any more.
(not under my build on Fedora Linux at least, and also [this](https://stackoverflow.com/questions/68280375/is-there-any-way-to-communicate-with-the-spotify-client-locally) stack overflow post states that it was removed)

Maybe putting a warning on crates.io would be nice so others don't have to waste their time 😜

**Comment by SplittyDev** [comment]
Yep, I suppose I should find some time to make a new release with a warning in the README..

It's quite sad that Spotify decided to remove the Local API, since it was quite powerful, didn't require any fancy cloud stuff, and worked for Spotify Free as well as Premium. Nowadays, I think the only way forward is the Web API which requires a developer account (and iirc a Premium subscription).

Maybe it's a good thing in the end. I haven't properly maintained this library in a long time (only did a small update to fix compilation on more recent Rust versions), and the code is far from ideal. When I released the last actively maintained version, async Rust wasn't a thing yet, and if I wrote it today, the code would surely be a lot nicer.

**Comment by SplittyDev** [comment]
Done, see #9.

**Comment by embediver** [comment]
Awesome, that was fast!

And thanks for the poem, made me laugh.

**Comment by SplittyDev** [comment]
@MG-96 I just realized I could use this opportunity to finish my last Hacktoberfest PR, so.. two birds with one stone haha.

Thanks for reminding me about updating the crate, have a good one!
